/** Tokens permitidos en plantillas del CMS — alineados con ctx.vars del teleprompter. */
export const TELEPROMPTER_TOKEN_REGISTRY = [
  "saludo",
  "nombre_cliente",
  "cliente_nombre",
  "cliente_primer_nombre",
  "rut",
  "telefono",
  "correo",
  "direccion",
  "direccion_completa",
  "region",
  "comuna",
  "fecha_contratacion",
  "fecha_venta",
  "fecha",
  "tipo_venta",
  "numero_portar",
  "linea_principal",
  "operador_actual",
  "plan",
  "valor_plan",
  "beneficios",
  "promociones",
  "promociones_lista",
  "resumen_multilinea",
  "lineas",
  "cantidad_lineas",
  "cantidad_lineas_adicionales",
  "valor_linea_principal",
  "valor_linea_adicional",
  "valor_total",
  "total_mensual",
  "gb",
  "roaming",
  "apps_libres",
  "club_wom",
  "pedidosya",
  "cupon_equipos",
  "cuotas_gratis",
  "equipo",
  "pie",
  "cuotas",
  "valor_cuota",
  "valor_equipo_total",
  "valor_total_equipo",
  "caracteristicas_equipo",
  "fecha_entrega",
  "tipo_entrega",
  "nombre_sucursal",
  "direccion_sucursal",
  "horario_sucursal",
  "codigo_retiro",
  "correo_ejecutivo",
  "nombre_ejecutivo",
  "ejecutivo",
  "observaciones",
  "condiciones_especiales",
  "numero_nuevo",
] as const;

export type TeleprompterTokenName = (typeof TELEPROMPTER_TOKEN_REGISTRY)[number];

const TOKEN_SET = new Set<string>(TELEPROMPTER_TOKEN_REGISTRY);

export function isKnownTeleprompterToken(name: string): boolean {
  return TOKEN_SET.has(name);
}

export const TELEPROMPTER_TOKEN_LABELS: Record<string, string> = {
  saludo: "Saludo contextual",
  nombre_cliente: "Nombre completo del cliente",
  cliente_primer_nombre: "Primer nombre del cliente",
  rut: "RUT",
  telefono: "Teléfono",
  correo: "Correo electrónico",
  direccion: "Dirección",
  plan: "Nombre del plan",
  valor_plan: "Valor del plan",
  numero_portar: "Número a portar",
  numero_nuevo: "Número nuevo",
  fecha_entrega: "Fecha de entrega",
  nombre_ejecutivo: "Nombre del ejecutivo",
  correo_ejecutivo: "Correo del ejecutivo",
  promociones: "Promociones",
  beneficios: "Beneficios",
  operador_actual: "Operador actual",
  tipo_entrega: "Tipo de entrega",
};
